server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    user:
      name: abc
      password: 123

mybatis:
  mapper-locations: classpath:mapper/*.xml


#logging:
#  level: trace
